spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: 1.3.0
accounts:
  details: "Prod Microservice for Accounts"
  contact-info:
    email: "test@gmail"
    location: "Pune"
  phone-no:
    num1: "123123123"
    num2: "321321321"