services:
#  rabbit:
#    image: rabbitmq:3-management
#    hostname: "rabbitmq"
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    networks:
#      - eazybytes
  configserver:
    image: akashganga333/configserver:v4
    container_name: configserver-ms
    ports:
      - "8071:8071"
#    depends_on:
#      rabbit:
#        condition: service_healthy
#    environment:
#      SPRING_RABBITMQ_HOST: "rabbit"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      retries: 10
      interval: 10s
      timeout: 5s
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybytes
  eurekaserver:
    image: akashganga333/eurekaserver:v4
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      retries: 10
      interval: 10s
      timeout: 5s
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybytes
  accounts:
    image: akashganga333/accounts:v4
    container_name: accounts-ms
    ports:
      - "8081:8081"
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
      SPRING_RABBITMQ_HOST: "rabbit"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybytes
  cards:
    image: akashganga333/cards:v4
    ports:
      - "9000:9000"
    container_name: cards-ms
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
      SPRING_RABBITMQ_HOST: "rabbit"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybytes
  loans:
    image: akashganga333/loans:v4
    ports:
      - "8090:8090"
    container_name: loans-ms
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
      SPRING_RABBITMQ_HOST: "rabbit"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybytes
networks:
  eazybytes:
    driver: "bridge"

